# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - cnpjapidotnet

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://index.docker.io/v1/
        username: ${{ secrets.AzureAppService_ContainerUsername_3ba9c178acb8426f8da21de7b13d1692 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_56f2125f61d64fa989e12ec0d1a30a9b }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: index.docker.io/${{ secrets.AzureAppService_ContainerUsername_3ba9c178acb8426f8da21de7b13d1692 }}/cnpj-api-csharp:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v3
      with:
        app-name: 'cnpjapidotnet'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_e9edeef0d49c4b17aeab0650cb69271e }}
        images: 'index.docker.io/${{ secrets.AzureAppService_ContainerUsername_3ba9c178acb8426f8da21de7b13d1692 }}/cnpj-api-csharp:${{ github.sha }}'